### ISSUE TITLE
Pip install problem on Windows

### ISSUE THREAD

**Issue by wbinek** [jruizgit/rules#57]
Hello,

I am trying to install durable_rules on Windows and use it with python 2.7. When I try to run: 
>py -2.7 -m pip install "durable_rules"

I get following error:

>C:\Users\wojci\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG /Tcdeps/Win32_Interop/win32_error.c /Fobuild\temp.win-amd64-2.7\deps/Win32_Interop/win32_error.obj
    win32_error.c
    c1 : fatal error C1083: Cannot open source file: 'deps/Win32_Interop/win32_error.c': No such file or directory
    error: command 'C:\\Users\\wojci\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

How to fix this issue?

Thanks for any help!

**Comment by jruizgit** [comment]
Hi, thank you for reporting the problem. This is a known issue. Currently only the node.js install of durable_rules is supported in Windows. durable_rules relies on hiredis, which is available in Windows compiled with the VS 10.0 or VS 14.0 toolsets. Unfortunately Python 2.7 still relies on the VS 9.0 toolset, which has a different set of header files.

We have two options at this point:
1. Fork hiredis to compile using VS 9.0 toolset
2. Implement support for Python 3.x in all operating systems

Option #1 is not my favorite as it would be very difficult to keep up to date.  #2 seems like a good investment as durable_rules would be available to all Python 3.x users.

What do you think?

**Comment by d-cooper** [comment]
Hi! Thanks for the answer. Supporting Python 3 sounds like a better solution for future development. 

I've found the information that it is possible to run durable_rules for testing in Bash for Windows. It installed properly, but when I try to run a Hello World program I get Segmentation fault on run_all(). Do you know if there is any way to fix it?

**Comment by d-cooper** [comment]
I tried durable_rules 0.33.77 from pip and it works fine.

**Comment by jruizgit** [comment]
Quick update on this: I just completed the changes and tests required to support Python 3.5 in Windows. You need to install VC++ 14 (see https://wiki.python.org/moin/WindowsCompilers). Using a C++ terminal (the shortcuts are installed by the VC++ installer), you can do `pip install durable_rules`. Please make sure you use the 64 bit terminal if you installed Python 64 bit build.

**Comment by d-cooper** [comment]
Sorry for the late answer. I tested it and works fine now :)
