### PR TITLE
fix: add compatibility with Python 3.13 by replacing deprecated PyEval_CallObject

### PR DESCRIPTION
**Pull request by tomaquet18**
### Summary

This PR replaces all occurrences of the deprecated `PyEval_CallObject` with `PyObject_CallObject` in the `rules.c` file.

### Motivation

Starting from **Python 3.13**, `PyEval_CallObject` has been **removed from the CPython C API**, which causes a linker error during build:
`unresolved external symbol PyEval_CallObject`
To ensure compatibility with Python 3.13 and future releases, this change switches to the officially supported `PyObject_CallObject`, which works on all Python versions from 3.6 onwards.

### Compatibility

 `PyObject_CallObject` is fully backward compatible, so this change does not introduce any breaking behavior.

### References

- [Python 3.13 What's New](https://docs.python.org/3/whatsnew/3.13.html)
- [PyObject_CallObject documentation](https://docs.python.org/3/c-api/call.html#c.PyObject_CallObject)

### CODE REVIEW

**Comment by jruizgit** [comment]
Thanks a lot for looking into this.
